/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
export const DataTableModuleNgFactory:i0.NgModuleFactory<i1.DataTableModule> = i0.ɵcmf(i1.DataTableModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i1.DataTableModule,i1.DataTableModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUGhpbGlwcGUuVmVycG9vdGVuL0Rvd25sb2Fkcy9hbmd1bGFyNC1kYXRhdGFibGUtYm9vdHN0cmFwLTQtZml4ZWQtbWFzdGVyL2FuZ3VsYXI0LWRhdGF0YWJsZS1ib290c3RyYXAtNC1maXhlZC1tYXN0ZXIvc3JjL2luZGV4Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1BoaWxpcHBlLlZlcnBvb3Rlbi9Eb3dubG9hZHMvYW5ndWxhcjQtZGF0YXRhYmxlLWJvb3RzdHJhcC00LWZpeGVkLW1hc3Rlci9hbmd1bGFyNC1kYXRhdGFibGUtYm9vdHN0cmFwLTQtZml4ZWQtbWFzdGVyL3NyYy9pbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
